---
- hosts: localhost
  connection: local
  gather_facts: False
  roles:
  - role: awsec2

- hosts: tag_html_html_pages
  gather_facts: False
  remote_user: ubuntu
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ private_key }}"
  roles:
  - role: common
  - role: webserver