---
# vars file for webserver
key_path: /etc/ssl/private
cert_path: /etc/ssl/certs
key: "{{ key_path }}/apache-selfsigned.key"
csr: "{{ cert_path }}/apache-selfsigned.csr"
cert: "{{ cert_path }}/apache-selfsigned.crt"
dhparam: "{{ cert_path }}/dhparam.pem"
config_path: /etc/apache2/
ssl_config: "{{ config_path }}/conf-available/ssl.conf"
non_ssl_config: "{{ config_path }}/non-ssl.conf"
httpd_config: /etc/apache2/apache2.conf
docroot: /var/www/html