---
# handlers file for common
- name: Restart chrony
  service:
    name: chrony
    state: restarted

- name: Enable and start chrony
  service:
    name: chrony
    enabled: yes
    state: started

- name: Enable and start sshd
  service:
    name: sshd
    enabled: yes
    state: started

- name: Restart sshd
  service:
    name: sshd
    state: restarted