---
# handlers file for common
- name: Restart chronyd
  service:
    name: chronyd
    state: restarted

- name: Enable and start chrony
  service:
    name: chronyd
    enabled: yes
    state: started

- name: Enable and start sshd
  service:
    name: sshd
    enabled: yes
    state: started

- name: Restart sshd
  service:
    name: sshd
    state: restarted