---
- name: Install openssh
  apt:
    name: openssh-server
    state: present
  notify: Enable and start sshd

- name: Install sshd_config template
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Restart sshd

- name: Install ubuntu sshd file
  template:
    src: sshd.rhel8
    dest: /etc/ssh/sshd
    owner: root
    group: root
    mode: 0640