---
- name: check directory
  stat:
    path: "{{ docroot }}"
  register: dir_data

- name: Creates directory "{{ docroot }}"
  file:
    path: "{{ docroot }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'
  when: not dir_data.stat.exists

- name: Install virtual host template
  template:
    src: virtual_host.conf.j2
    dest: "{{ config_path }}/{{ inventory_hostname }}.conf"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Restart httpd