---
pool_servers: [ 
  pool 0.ubuntu.pool.ntp.org iburst
  pool 1.ubuntu.pool.ntp.org iburst
  pool 2.ubuntu.pool.ntp.org iburst
  pool 3.ubuntu.pool.ntp.org iburst
  ]
timezone: Australia/Melbourne
packages_present: [
  aptitude,
  sysstat,
  coreutils,
  man,
  openssl,
  vim,
  python3-apt,
  man-db,
  unzip
]
packages_absent: []

# ssh vars
permitrootlogin: 'no'
passwordAuthentication: 'yes'
clientaliveinterval: 180
x11forwarding: 'no'
sftp_server: /usr/libexec/openssh/sftp-server
print_motd: 'yes'
listenaddress: []
options: []
challengeresponseauthentication: 'no'
pubkeyauthentication: 'yes'
twofaenabled: 'false'
blockposix_enabled: 'false'
privileged_proxy_accounts: privileged_proxy_accounts
maxstartups: 10:30:60
maxsessions: 4